ROOT_DIR = "./"
DATA_DIR = "./data/"

# Preprocessing
USER_RATING_CUTOFF = 25
ANIME_RATING_CUTOFF = 50
DROPPED_PCT_CUTOFF = 0.5

# Training
BATCH_SIZE = 1024
USER_EMBED_DIM = 20
ANIME_EMBED_DIM = 20
LEARNING_RATE = 0.001
WEIGHT_DECAY = 1e-5
EPOCHS = 20

# Content-Based Filtering
GENRE_WEIGHT = 0.775
TYPE_WEIGHT = 0.225